version: '3.8'

networks:
  monitoring:
    driver: bridge

volumes:
  alertmanager_data:


services:
  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    ports:
      - 9100:9100
    expose:
      - 9100
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus:/etc/prometheus
      - /home/cra/prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.min-block-duration=2h'
    ports:
      - 9090:9090
    expose:
      - 9090
    networks:
      - monitoring

  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    restart: unless-stopped
    ports:
      - 9093:9093
    volumes:
      - ./alertmanager/alertmanager.yml:/config/alertmanager.yml
      - alertmanager_data:/data
    command: '--config.file=/config/alertmanager.yml --log.level=debug'
  # node-application-monitoring-app:
  #   build:
  #     context: node-application-monitoring-app
  #   ports:
  #     - 8000:8000
  #   expose:
  #     - 8000
  #   networks:
  #     - monitoring
