# global:
#   scrape_interval: 5s
#   scrape_timeout: 5s
#   evaluation_interval: 1m
# scrape_configs:
#   - job_name: node-application-monitoring-app
#     honor_timestamps: true
#     scrape_interval: 5s
#     scrape_timeout: 5s
#     metrics_path: /metrics
#     scheme: http
#     static_configs:
#       - targets: ["172.17.0.1:8000"]

global:
  scrape_interval: 1m
  scrape_timeout: 10s

rule_files:
  - alert.rules

alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets: ["alertmanager:9093"]

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 1m
    static_configs:
      - targets:
          - "localhost:9090"
          - "idonotexists:564"

  - job_name: "node"
    static_configs:
      - targets: ["node-exporter:9100"]
