apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-logs
spec:
  volumeName: prometheus-logs
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 5Gi
